/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package github;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        mainBankSystem classUnderTest = new mainBankSystem();
        assertNotNull(classUnderTest, "app should have a greeting");
    }
}
